### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by noahggarrett-1** [person1234-ux/evanserver#2]
1. No stealing
2. No Griefing property or players
3.Do not be toxic or bully others
4. No potty words
5. No inappropriate builds
6. No cheating or using mods outside of client like lunar or bad lion
7.No duplicating items
8. All damaged property must be replaced
9. Shops must be fairly priced and no stealing or taking items without paying.
10. Do not make lag farms or builds intended to cause major lag.
11. No hogging, hoarding or intentionally killing animals to prevent others from obtaining them.

**Comment by person1234-ux** [comment]
rules have been added
